env:
  matrix:
  - GOPATH=$TRAVIS_BUILD_DIR/gosrc
  global:
  - secure: g9R/BW+1XntQCVjtJyi0pPRiYMqbv3NyH2hfMWj8OBnreGwogYG/JlzZoRc9qWOMjXSTFdku8oRCAwmKR/kulG5awcYagDCgil5Leqvrl1zHbP5/biE2ht/iQBMneiC3M0S5qvJqw+useCVraxUxjL61ssdyfacvexAlzjeN1l4TmssQvKWUDJD2UirWlF9o4iwEtJtVnIQoelTqc2nAB9o3Letu9v8qANDClxwAc7WTXpyjG2OTTcvygisndzqoTwZNkMWMZehqUGa54ag7goeQ+R/cRbvDor5YX0oxdjc2afITIBPof4VBeu3KJOVcKJrsUwxzzBG9bL5jKJqjUJ7bjItyy+N4fVvXg5+/zJucsQ/NsfVr5ACUEkcl1B4Ppy9FnYpAfY8RyHkRzuntxk509pjSGFBNZIJPWQs3TFVStdE9ZGwkcZpumf3htQrXiC1MQOOIhwqIQbxow8xZFf03P/HTa7d8N+/u4EhI0NOb6xdr+6W63TW96Tuz7Fc/ffXe3RDtFSLesX2yzxfw/Um88qzoAXPTxVcfcaRVNeOSFnWp0VWaHuD1RCAw6EcONJSXINsOONKa/uU3aELcbvn+S3EsUvwUvj1d2atIiViIS7lFpWzzE8PIRgm+B7mV48HnbL4C6dIv0b9lZ1Zidcc0K6r+nbExvdkocpRf9Oc=
  - secure: LcDRrJEXOuyX9Kb6D1dqDiYcfhAn/ZvFLMdyNXAaPczawanAkqOqqIzKDQd4i3/cVuQ9R09tHrozchAFKU0qepm+IW/t+UrSkP2lhaspStRt5atZoSE1HRdF+r27UgGxrPT5tTHgKi3+MOiFYNezKsOx7bX10C4mp5y9myhXObHBxQ0yS79kQOsFGxxl+qYNhIOPUw7lTAo1/DkqNmEPKHd6IDJSsOSi/4sYxB0RpbTz4tKEuSF8VHDjTxfLkX9OJeo2shXbEyUCULmybEsxTk8lZo+dqL0BB8/o3J6EJ4T+rqc9HiENxeAsugyQ2vMMdD/siBHo/IyTZN3PHBGgZKt/pL9B4wluzQPLvMtRoHDsw2UiEaBlZNmkEJukdvnnwB2Z1AFSi1keJiEZ64ABVWuh4wlFijlT5TyCcRV+7EhYaXj8hpmNNv7DU4aKdH3gq+shEpPtAj2s9uaLyrCFH+oAhZOC5M6Qdp57fUDB8M1N4V6Ki3/TQh4PvvKl06H6m0VKlHWoK08eiefYnwX9sZHgnhHCJL7IiRncYAEPyDD5kL83K2Fyd6vCN8iMa4OZBCb2YmR5bI7QzYrxLIKob6fz8gLUM+U7+KFdNdBKpGGsHt2gtXR67u/0Y3lkvsdAWWvh6bEhSpNnIby23RsMx9xUc7V3d+LUNH4VIfp8tLc=
install:
- mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
- mkdir -p "$TRAVIS_BUILD_DIR/static"
- curl -s https://www.parse.com/downloads/cloud_code/installer.sh | sudo /bin/bash
- go get -v github.com/jrbaudin/CobraCup
script: ./scripts/build_all.sh
# blacklist
branches:
  except:
    - develop
    - production
    - develop-workcup

# whitelist
branches:
  only:
    - develop-cobra-cup-2016-production
    - develop-cobra-cup-2016-development
