env:
  matrix:
  - GOPATH=$TRAVIS_BUILD_DIR/gosrc
# blacklist
branches:
  except:
    - develop
    - production
    - develop-workcup
    - develop-cobra-cup-2016-development
# whitelist
branches:
  only:
    - develop-cobra-cup-2016-production
install:
- mkdir -p "$TRAVIS_BUILD_DIR/gosrc"
- mkdir -p "$TRAVIS_BUILD_DIR/static"
- curl -s https://www.parse.com/downloads/cloud_code/installer.sh | sudo /bin/bash
before_script:
- chmod +x ./scripts/build_all.sh
script: ./scripts/build_all.sh
sudo: required
